# Generated by Django 3.1.3 on 2020-11-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoitem',
            name='id1',
        ),
    ]
